### ISSUE TITLE
Not working with Sails 1.0 without using Wetland

### ISSUE THREAD

**Issue by vsiguero** [SpoonX/sails-hook-authorization#29]
Hi, when using Sails 1.0.0-37 and Waterline (not Wetland) I get this error when posting to /auth/login:

TypeError: sails.models.user[("findOneBy" + _.upperFirst(...))] is not a function.

Do we have to write our custom actions in our own User model?

**Comment by RWOverdijk** [comment]
@vsiguero For sails 1? Yes. They removed those magic (and imo disgusting) methods.

**Comment by RWOverdijk** [comment]
@vsiguero https://github.com/balderdashy/sails-docs/blob/1.0/upgrading/To1.0.md#other-breaking-changes

> Dynamic finders (such as User.findById()) are no longer added to your models automatically. You can implement these yourself as custom model methods.
